// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD8mUynMZazSww9R9Hb2Bt-x1uXa8esyY',
    appId: '1:137383416740:web:e3876df4f396248b02e731',
    messagingSenderId: '137383416740',
    projectId: 'mxpertz-d43ee',
    authDomain: 'mxpertz-d43ee.firebaseapp.com',
    storageBucket: 'mxpertz-d43ee.firebasestorage.app',
    measurementId: 'G-EFLGLPBHVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUYAFJjPGt5PIX-BcbsIyTte_AaO-ngRQ',
    appId: '1:137383416740:android:0b0c9f262edad85202e731',
    messagingSenderId: '137383416740',
    projectId: 'mxpertz-d43ee',
    storageBucket: 'mxpertz-d43ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtmZs38lOa2PpXCxopo12QJzM08J8D4XU',
    appId: '1:137383416740:ios:2b026cda86572a2802e731',
    messagingSenderId: '137383416740',
    projectId: 'mxpertz-d43ee',
    storageBucket: 'mxpertz-d43ee.firebasestorage.app',
    iosBundleId: 'com.example.mxpertz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtmZs38lOa2PpXCxopo12QJzM08J8D4XU',
    appId: '1:137383416740:ios:2b026cda86572a2802e731',
    messagingSenderId: '137383416740',
    projectId: 'mxpertz-d43ee',
    storageBucket: 'mxpertz-d43ee.firebasestorage.app',
    iosBundleId: 'com.example.mxpertz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD8mUynMZazSww9R9Hb2Bt-x1uXa8esyY',
    appId: '1:137383416740:web:af9dc009f6edc3d902e731',
    messagingSenderId: '137383416740',
    projectId: 'mxpertz-d43ee',
    authDomain: 'mxpertz-d43ee.firebaseapp.com',
    storageBucket: 'mxpertz-d43ee.firebasestorage.app',
    measurementId: 'G-WNLJJDP7BE',
  );
}
